cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'pyenv'

cask '1password'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
